export const Initial_State = {
    users: [{id: 11, name: 'admin', username: 'admin', email: 'denied', phone: 'denied'}],
    counter: 11,
    usernames: ['Leanne','Ervin','Clementine','Patricia','Chelsey','Dennis','Kurtis','Nicholas','Glenna','Clementina','admin'],
    Logged_In: false,
    Admin: false,
    Username: null,
    UserLogin: null,
    newUser: null,
    UserLoggedIn: false,
    Initial_Header: [
    {id:1, text: "На главную", path: '/'},
    {id:2, text: "О создателе", path: '/Creator'},
    {id:3, text: "Пользователи", path: '/Users'},
    {id:4, text: "Статьи", path: '/Topics'},
    ],
    UsersLoading: false,
    UserLoadingError: null,
    topics: [],
    newUserName: null,
    newUserSurName: null,
    newUserMail: null,
    newUserPhone: null,
    newUserRegistrationSuccess: false,
    UserAlreadyExists: false,
    UsersAlreadyLoaded: false,
    AddNewTopic: false,
    TopicBody: '',
    TopicHeader: '',
    comments: [],
    CommentsLoading: false,
    CommentsLoadingError: null,
    CommentsLoaded: false,
    CommentBody: '',
    images: [],
    ImagesLoading: false,
    ImagesError: null,
    ImagesAlreadyLoaded: false,
 }